// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: shopcart.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelShopCartItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int32 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	ProductId int32 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *DelShopCartItem) Reset() {
	*x = DelShopCartItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelShopCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelShopCartItem) ProtoMessage() {}

func (x *DelShopCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelShopCartItem.ProtoReflect.Descriptor instead.
func (*DelShopCartItem) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{0}
}

func (x *DelShopCartItem) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DelShopCartItem) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ShopCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId int32 `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	ProductId int32 `protobuf:"varint,3,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32 `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Checked   bool  `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
}

func (x *ShopCartReq) Reset() {
	*x = ShopCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCartReq) ProtoMessage() {}

func (x *ShopCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCartReq.ProtoReflect.Descriptor instead.
func (*ShopCartReq) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{1}
}

func (x *ShopCartReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopCartReq) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ShopCartReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ShopCartReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ShopCartReq) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type CartItemListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total    int32          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ItemList []*CartItemRes `protobuf:"bytes,2,rep,name=itemList,proto3" json:"itemList,omitempty"`
}

func (x *CartItemListRes) Reset() {
	*x = CartItemListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItemListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemListRes) ProtoMessage() {}

func (x *CartItemListRes) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemListRes.ProtoReflect.Descriptor instead.
func (*CartItemListRes) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{2}
}

func (x *CartItemListRes) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CartItemListRes) GetItemList() []*CartItemRes {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type CartItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId int32 `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	ProductId int32 `protobuf:"varint,3,opt,name=productId,proto3" json:"productId,omitempty"`
	Num       int32 `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Checked   bool  `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
}

func (x *CartItemRes) Reset() {
	*x = CartItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRes) ProtoMessage() {}

func (x *CartItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRes.ProtoReflect.Descriptor instead.
func (*CartItemRes) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{3}
}

func (x *CartItemRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemRes) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CartItemRes) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItemRes) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CartItemRes) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type AccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int32 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *AccountReq) Reset() {
	*x = AccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopcart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReq) ProtoMessage() {}

func (x *AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_shopcart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReq.ProtoReflect.Descriptor instead.
func (*AccountReq) Descriptor() ([]byte, []int) {
	return file_shopcart_proto_rawDescGZIP(), []int{4}
}

func (x *AccountReq) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_shopcart_proto protoreflect.FileDescriptor

var file_shopcart_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x70, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a,
	0x0b, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x28, 0x0a,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x52, 0x08, 0x69,
	0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x22,
	0x2a, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x32, 0xef, 0x01, 0x0a, 0x0f,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0c, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x12, 0x3a, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0c, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shopcart_proto_rawDescOnce sync.Once
	file_shopcart_proto_rawDescData = file_shopcart_proto_rawDesc
)

func file_shopcart_proto_rawDescGZIP() []byte {
	file_shopcart_proto_rawDescOnce.Do(func() {
		file_shopcart_proto_rawDescData = protoimpl.X.CompressGZIP(file_shopcart_proto_rawDescData)
	})
	return file_shopcart_proto_rawDescData
}

var file_shopcart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shopcart_proto_goTypes = []interface{}{
	(*DelShopCartItem)(nil), // 0: DelShopCartItem
	(*ShopCartReq)(nil),     // 1: ShopCartReq
	(*CartItemListRes)(nil), // 2: CartItemListRes
	(*CartItemRes)(nil),     // 3: CartItemRes
	(*AccountReq)(nil),      // 4: AccountReq
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_shopcart_proto_depIdxs = []int32{
	3, // 0: CartItemListRes.itemList:type_name -> CartItemRes
	4, // 1: ShopCartService.ShopCartItemList:input_type -> AccountReq
	1, // 2: ShopCartService.AddShopCartItem:input_type -> ShopCartReq
	1, // 3: ShopCartService.UpdateShopCartItem:input_type -> ShopCartReq
	0, // 4: ShopCartService.DeleteShopCartItem:input_type -> DelShopCartItem
	2, // 5: ShopCartService.ShopCartItemList:output_type -> CartItemListRes
	3, // 6: ShopCartService.AddShopCartItem:output_type -> CartItemRes
	5, // 7: ShopCartService.UpdateShopCartItem:output_type -> google.protobuf.Empty
	5, // 8: ShopCartService.DeleteShopCartItem:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shopcart_proto_init() }
func file_shopcart_proto_init() {
	if File_shopcart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shopcart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelShopCartItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItemListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopcart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shopcart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopcart_proto_goTypes,
		DependencyIndexes: file_shopcart_proto_depIdxs,
		MessageInfos:      file_shopcart_proto_msgTypes,
	}.Build()
	File_shopcart_proto = out.File
	file_shopcart_proto_rawDesc = nil
	file_shopcart_proto_goTypes = nil
	file_shopcart_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShopCartServiceClient is the client API for ShopCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopCartServiceClient interface {
	// 购物车列表
	ShopCartItemList(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*CartItemListRes, error)
	// 添加产品的购物车
	AddShopCartItem(ctx context.Context, in *ShopCartReq, opts ...grpc.CallOption) (*CartItemRes, error)
	// 更新购物车内的产品
	UpdateShopCartItem(ctx context.Context, in *ShopCartReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除购物车内的某个产品
	DeleteShopCartItem(ctx context.Context, in *DelShopCartItem, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type shopCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopCartServiceClient(cc grpc.ClientConnInterface) ShopCartServiceClient {
	return &shopCartServiceClient{cc}
}

func (c *shopCartServiceClient) ShopCartItemList(ctx context.Context, in *AccountReq, opts ...grpc.CallOption) (*CartItemListRes, error) {
	out := new(CartItemListRes)
	err := c.cc.Invoke(ctx, "/ShopCartService/ShopCartItemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartServiceClient) AddShopCartItem(ctx context.Context, in *ShopCartReq, opts ...grpc.CallOption) (*CartItemRes, error) {
	out := new(CartItemRes)
	err := c.cc.Invoke(ctx, "/ShopCartService/AddShopCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartServiceClient) UpdateShopCartItem(ctx context.Context, in *ShopCartReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ShopCartService/UpdateShopCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCartServiceClient) DeleteShopCartItem(ctx context.Context, in *DelShopCartItem, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ShopCartService/DeleteShopCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopCartServiceServer is the server API for ShopCartService service.
type ShopCartServiceServer interface {
	// 购物车列表
	ShopCartItemList(context.Context, *AccountReq) (*CartItemListRes, error)
	// 添加产品的购物车
	AddShopCartItem(context.Context, *ShopCartReq) (*CartItemRes, error)
	// 更新购物车内的产品
	UpdateShopCartItem(context.Context, *ShopCartReq) (*emptypb.Empty, error)
	// 删除购物车内的某个产品
	DeleteShopCartItem(context.Context, *DelShopCartItem) (*emptypb.Empty, error)
}

// UnimplementedShopCartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopCartServiceServer struct {
}

func (*UnimplementedShopCartServiceServer) ShopCartItemList(context.Context, *AccountReq) (*CartItemListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShopCartItemList not implemented")
}
func (*UnimplementedShopCartServiceServer) AddShopCartItem(context.Context, *ShopCartReq) (*CartItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShopCartItem not implemented")
}
func (*UnimplementedShopCartServiceServer) UpdateShopCartItem(context.Context, *ShopCartReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShopCartItem not implemented")
}
func (*UnimplementedShopCartServiceServer) DeleteShopCartItem(context.Context, *DelShopCartItem) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShopCartItem not implemented")
}

func RegisterShopCartServiceServer(s *grpc.Server, srv ShopCartServiceServer) {
	s.RegisterService(&_ShopCartService_serviceDesc, srv)
}

func _ShopCartService_ShopCartItemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServiceServer).ShopCartItemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCartService/ShopCartItemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServiceServer).ShopCartItemList(ctx, req.(*AccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCartService_AddShopCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServiceServer).AddShopCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCartService/AddShopCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServiceServer).AddShopCartItem(ctx, req.(*ShopCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCartService_UpdateShopCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopCartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServiceServer).UpdateShopCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCartService/UpdateShopCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServiceServer).UpdateShopCartItem(ctx, req.(*ShopCartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCartService_DeleteShopCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelShopCartItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCartServiceServer).DeleteShopCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShopCartService/DeleteShopCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCartServiceServer).DeleteShopCartItem(ctx, req.(*DelShopCartItem))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopCartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShopCartService",
	HandlerType: (*ShopCartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShopCartItemList",
			Handler:    _ShopCartService_ShopCartItemList_Handler,
		},
		{
			MethodName: "AddShopCartItem",
			Handler:    _ShopCartService_AddShopCartItem_Handler,
		},
		{
			MethodName: "UpdateShopCartItem",
			Handler:    _ShopCartService_UpdateShopCartItem_Handler,
		},
		{
			MethodName: "DeleteShopCartItem",
			Handler:    _ShopCartService_DeleteShopCartItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopcart.proto",
}
